import { mysqlTable, mysqlSchema, AnyMySqlColumn, index, int, varchar, text, unique } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const gbBbMaxxHindi = mysqlTable("gb_bb_maxx_hindi", {
	id: int().autoincrement().notNull(),
	apiLeadId: varchar("api lead id", { length: 255 }).default('NULL'),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	shipping: text().notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbDeAddictionHindi = mysqlTable("gb_de_addiction_hindi", {
	id: int().autoincrement().notNull(),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	shipping: text().notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbDivitizHindi = mysqlTable("gb_divitiz_hindi", {
	id: int().autoincrement().notNull(),
	apiLeadId: varchar("api lead id", { length: 255 }).default('NULL'),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbDivitizTamil = mysqlTable("gb_divitiz_tamil", {
	id: int().autoincrement().notNull(),
	apiLeadId: varchar("api lead id", { length: 255 }).default('NULL'),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbHammerLpTestMalay = mysqlTable("gb_hammer-lp-test-malay", {
	id: int().autoincrement().notNull(),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbHerbalThorexGujrati = mysqlTable("gb_herbal-thorex-gujrati", {
	id: int().autoincrement().notNull(),
	apiLeadId: varchar("api lead id", { length: 255 }).notNull(),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	shipping: text().notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
	unique("api_lead_id_idx").on(table.apiLeadId),
]);

export const gbHerbalThorexHindi = mysqlTable("gb_herbal-thorex-hindi", {
	id: int().autoincrement().notNull(),
	apiLeadId: varchar("api lead id", { length: 255 }).notNull(),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	shipping: text().notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
	unique("api_lead_id_idx").on(table.apiLeadId),
]);

export const gbKetoPlusHindi = mysqlTable("gb_keto_plus_hindi", {
	id: int().autoincrement().notNull(),
	apiLeadId: varchar("api lead id", { length: 255 }).default('NULL'),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbKnightKingGoldTamil = mysqlTable("gb_knight-king-gold-tamil", {
	id: int().autoincrement().notNull(),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	shipping: text().notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbKubDeepamTamil = mysqlTable("gb_kub-deepam-tamil", {
	id: int().autoincrement().notNull(),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	shipping: text().notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbLivedaEnglish = mysqlTable("gb_liveda-english", {
	id: int().autoincrement().notNull(),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	shipping: text().notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbMansPowerTelugu = mysqlTable("gb_mans-power-telugu", {
	id: int().autoincrement().notNull(),
	apiLeadId: varchar("api lead id", { length: 255 }).default('NULL'),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	shipping: text().notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
	index("api_lead_id_idx").on(table.apiLeadId),
]);

export const gbManCareHindi = mysqlTable("gb_man_care_hindi", {
	id: int().autoincrement().notNull(),
	apiLeadId: varchar("api lead id", { length: 255 }).default('NULL'),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbManClickTamil = mysqlTable("gb_man_click_tamil", {
	id: int().autoincrement().notNull(),
	apiLeadId: varchar("api lead id", { length: 255 }).default('NULL'),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbMenXMalay = mysqlTable("gb_men-x-malay", {
	id: int().autoincrement().notNull(),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	shipping: text().notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbMenXTamil = mysqlTable("gb_men-x-tamil", {
	id: int().autoincrement().notNull(),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	shipping: text().notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbMenXTelugu = mysqlTable("gb_men-x-telugu", {
	id: int().autoincrement().notNull(),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	shipping: text().notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbPowerXHindi = mysqlTable("gb_power-x_hindi", {
	id: int().autoincrement().notNull(),
	apiLeadId: varchar("api lead id", { length: 255 }).default('NULL'),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbPwrUpHindi = mysqlTable("gb_pwr_up_hindi", {
	id: int().autoincrement().notNull(),
	apiLeadId: varchar("api lead id", { length: 255 }).default('NULL'),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbPwrUpTamil = mysqlTable("gb_pwr_up_tamil", {
	id: int().autoincrement().notNull(),
	apiLeadId: varchar("api lead id", { length: 255 }).default('NULL'),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbSlimoVedaGujrati = mysqlTable("gb_slimo_veda_gujrati", {
	id: int().autoincrement().notNull(),
	apiLeadId: varchar("api lead id", { length: 255 }).notNull(),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	shipping: text().notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
	unique("api_lead_id_idx").on(table.apiLeadId),
]);

export const gbSpartanHindi = mysqlTable("gb_spartan_hindi", {
	id: int().autoincrement().notNull(),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	shipping: text().notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbStrongMenHindi = mysqlTable("gb_strong_men_hindi", {
	id: int().autoincrement().notNull(),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	shipping: text().notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);

export const gbXenoProstHindi = mysqlTable("gb_xeno_prost_hindi", {
	id: int().autoincrement().notNull(),
	apiLeadId: varchar("api lead id", { length: 255 }).default('NULL'),
	domain: varchar({ length: 255 }).notNull(),
	lpName: varchar("lp name", { length: 100 }).notNull(),
	lang: varchar({ length: 100 }).notNull(),
	productName: varchar("product name", { length: 200 }).notNull(),
	quantity: varchar({ length: 200 }).notNull(),
	price: varchar({ length: 200 }).notNull(),
	paymentType: varchar("payment type", { length: 100 }).notNull(),
	name: varchar({ length: 200 }).notNull(),
	phone: varchar({ length: 20 }).notNull(),
	ip: varchar({ length: 200 }).notNull(),
	country: varchar({ length: 200 }).notNull(),
	region: varchar({ length: 200 }).notNull(),
	city: varchar({ length: 200 }).notNull(),
	address: varchar({ length: 500 }).notNull(),
	landmark: varchar({ length: 250 }).notNull(),
	pincode: varchar({ length: 200 }).notNull(),
	createdAt: varchar("created at", { length: 200 }).notNull(),
},
(table) => [
	index("domain_idx").on(table.domain),
]);
